# Si se modifica este archivo se debe reiniciar el servidor.

# La "secret_access_key" sirve para verificar la integridad de las cookies.
# Se generó mediante "rails secret".
development:
  secret_access_key: 8e164d80601a5e03d30fb0e7a50e65ca791adbe3bf0f627cf17dad163f516eb22a027770cd8da94e58306611f187929a946f03adbfbc27476e9b4feac1c53748

# Para el ambiente de producción se leerá desde las variables de entorno.
production:
  secret_access_key: <%= ENV['SECRET_ACCESS_KEY'] %>